# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('coun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lux_id', models.IntegerField()),
                ('lux_name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('Description', models.TextField()),
                ('address', models.TextField(default='Maadi')),
                ('longtiude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='Luxury_images', verbose_name='Image')),
                ('lux_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Luxury')),
            ],
        ),
        migrations.CreateModel(
            name='NewProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Address', models.TextField()),
                ('Services', models.TextField()),
                ('PaymentMethods', models.TextField()),
                ('DeliveryDate', models.TextField()),
                ('OwnerCompany', models.TextField()),
                ('longtiude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NewProjectsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='NewProjects_images', verbose_name='Image')),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.NewProjects')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('youtube', models.URLField(max_length=255)),
                ('phone', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('preview', models.TextField()),
                ('details', models.TextField()),
                ('longtiude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Categories')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.City')),
                ('country_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='property_images', verbose_name='Image')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_pro', to='project_app.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField()),
                ('unit_name', models.CharField(max_length=255)),
                ('min_area', models.FloatField()),
                ('max_area', models.FloatField()),
                ('minPrice', models.FloatField()),
                ('maxPrice', models.FloatField()),
                ('project_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='project_app.NewProjects')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='sec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Section'),
        ),
        migrations.AddField(
            model_name='property',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Property'),
        ),
        migrations.AddField(
            model_name='city',
            name='coun_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Country'),
        ),
    ]
