# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='longtiude',
            field=models.TextField(),
        ),
    ]
