# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(blank=True, upload_to='property_images')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Property')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
