# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20160405_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='coun_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pro', to=settings.AUTH_USER_MODEL),
        ),
    ]
