# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_property_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lux_id', models.IntegerField()),
                ('lux_name', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('Description', models.TextField()),
                ('longtiude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NewProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Address', models.TextField()),
                ('Services', models.TextField()),
                ('PaymentMethods', models.TextField()),
                ('DeliveryDate', models.TextField()),
                ('OwnerCompany', models.TextField()),
                ('longtiude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField()),
                ('unit_name', models.CharField(max_length=255)),
                ('min_area', models.FloatField()),
                ('max_area', models.FloatField()),
                ('minPrice', models.FloatField()),
                ('maxPrice', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='newprojects',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Units'),
        ),
    ]
