# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20160330_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='property_images', verbose_name='Image')),
                ('lux_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Luxury')),
            ],
        ),
        migrations.CreateModel(
            name='NewProjectsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='property_images', verbose_name='Image')),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.NewProjects')),
            ],
        ),
    ]
