# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_luxuryimage_newprojectsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxuryimage',
            name='image_name',
            field=models.ImageField(upload_to='Luxury_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newprojectsimage',
            name='image_name',
            field=models.ImageField(upload_to='NewProjects_images', verbose_name='Image'),
        ),
    ]
