# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20160330_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxury',
            name='address',
            field=models.TextField(default='Maadi'),
        ),
    ]
