# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20160330_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_pro', to='project_app.Property'),
        ),
    ]
